### ISSUE TITLE
[CQLReplicator on Glue] Reset replication

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#102]
`cql-replicator` can remember the status of replication.
If I want to delete all the data in a table and restart its replication from zero (but I don't want to run the cleanup command because I would affect all current running replications), what should I do?

**Comment by nwheeler81** [comment]
1. `--state request-stop`
2. in `cqlsh` or AWS Console run `delete from migration.ledger where ks='ks-name' and tbl='table-name'`
3. delete s3://your-landing-s3-bucket/ks-name/table-name
