### ISSUE TITLE
[CQLReplicator on Glue] Config to reduce replication lag

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#103]
Seems that the glue streaming job is running in micro batch.
Is there a way/configuration we can adjust to speed up the replication (i.e. reduce the replication lag)?

**Comment by nwheeler81** [comment]
The replication lag depends on `the number of tiles`, `WAIT_TIME` in `CQLReplicator.scala`, and the caching strategy in `CQLReplicator.scala`.
- Higher number of tiles reduces the replication lag, but increases pressure on the source.
- `WAIT_TIME` is 30 seconds but you can reduce it to the lower value, e.g. 10-5 seconds.
- The default caching strategy is `DISK_ONLY` that is slow but can handle large value of the primary keys, but you can change it to `MEMORY_AND_DISK_SER` **at your own risk** (there're some chances to get OOM, but you can mitigate it by setting the higher number of retries on the Glue job details).
