### ISSUE TITLE
[CQLReplicator on Glue] cassandra to AWS keyspaces replication - ran out of available IP address

### ISSUE THREAD

**Issue by frozensky** [aws-samples/cql-replicator#113]
**Describe the bug**
Ran out of IP address on the subnet

**To Reproduce**
1. run cqlreplicator with 40 tiles and each tiles running 56 workers, I assume each worker needs an IP address.  I have a /21 subnet which only have around 2000 IP available.  

2. See error
JobName:CQLReplicator and JobRunId:jr_fdeebc7dd067bea37ec946a9a83c2fe8d0b3da0e9b48f945e8561f7c0503eafc failed to execute with exception Number of IP addresses on subnet is 0: subnet-XXXXXXXXX (Service: AWSGlueJobExecutor; Status Code: 400; Error Code: InvalidInputException; Request ID: 410f9143-7427-423e-bd9c-3510d9136c2d; Proxy: null)

![Screenshot 2024-02-08 at 12 42 22 AM](https://github.com/aws-samples/cql-replicator/assets/4239718/1aa917e9-fb41-4a87-8b1c-0ad7e2b6fe04)

**Comment by frozensky** [comment]
I create 2nd connection on different subnet and attached to the job

**Comment by nwheeler81** [comment]
@frozensky I can do is to run a preflight check against `subnet-XXXXXXXXX` for available IPs.

**Comment by frozensky** [comment]
adding 2nd connection to the job works
