### ISSUE TITLE
[CQLReplicator on Glue] Handling of replication write error

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#115]
If during the replication, the writes to the target Amazon Keyspaces table failed for some records for some reason, how would `cql-replicator` handles that?

Example error:
- https://repost.aws/knowledge-center/keyspaces-http-5xx-errors

**Comment by nwheeler81** [comment]
@hungfaileung the CQLReplicator retires with the exponential backoff strategy (256 retires with the based delay 25ms and 1.1 multiplier), but you should plan ahead the incoming traffic and pre-warm/provision target resources to avoid retires.

**Comment by hungfaileung** [comment]
@nwheeler81 Is the retry talking about Glue job or individual write to target table?

**Comment by nwheeler81** [comment]
> @nwheeler81 Is the retry talking about Glue job or individual write to target table?

Individual writes and Glue job retires (default 1, but you can increase it)

**Comment by hungfaileung** [comment]
@nwheeler81 Thanks
