### ISSUE TITLE
migrate uncompressed data from Cassandra/Keyspaces to compressed Keyspaces

### ISSUE THREAD

**Issue by naveenkantamneni** [aws-samples/cql-replicator#117]
**Is your feature request related to a problem? Please describe.**
No. This is a new feature request

**Describe the solution you'd like**
It would be helpful to have compression option available when migrating from Cassandra to Keyspaces or from Keyspaces to compressed Keyspaces

**Describe alternatives you've considered**
Compress data during migration

**Additional context**
None.

**Comment by nwheeler81** [comment]
@naveenkantamneni 
[] Plan the JSON mapping what columns go "as is" and what columns should be serialized to JSON and compressed. The primary key stays the same.
[] Compression algorithms: LZ4 Fast Compressor, GZIP, ZSTD with different compression levels
