### ISSUE TITLE
Extra keyword and backslashes when using Compression

### ISSUE THREAD

**Issue by hindprak** [aws-samples/cql-replicator#143]
**Describe the bug**
When using compression on a single column, the cqlreplicator adds extra characters causing backward compatibility issues
 1) The field name of the source compressed column  is added to the actual compressed field value
 2) Backslashes is added to each of key/value element of the json data  

**To Reproduce**
Input compression configuration in cqlreplicator
      "compressionConfig": {
        "enabled": true,
        "compressAllNonPrimaryColumns": false,
        "compressNonPrimaryColumns": ["metadata"],
        "targetNameColumn": "metadata_compressed"
      }

Output of compression (after decompression) in the metadata_compressed field
'{"metadata":"{\\"deviceId\\":{\\"ndsId\\":\\"9af86174-2a42-11ec-8f03-b58eaeebc034\\"},\\"identifier\\":{\\"value\\":\\"123456789\\"}'

**Expected behavior**
{"deviceId":{"ndsId":"9af86174-2a42-11ec-8f03-b58eaeebc034"},"identifier":{"value":"123456789"}}

**Screenshots**

**Additional context**

**Comment by nwheeler81** [comment]
@hindprak I pushed the changes to this branch. Could you please validate and let me know the result

**Comment by hindprak** [comment]
Thanks @nwheeler81 . I will do a quick test

**Comment by hindprak** [comment]
@nwheeler81 A quick sanity check on one of tables we loaded, looks good. We will do a full functional test after loading all tables. Thank you very much.

**Comment by hindprak** [comment]
@nwheeler81 Functional test on compression/decompression works as expected. Thank you very much
