### ISSUE TITLE
Question: How does cqlreplicator behave if a row already exists on TARGET

### ISSUE THREAD

**Issue by jlewis-spotnana** [aws-samples/cql-replicator#148]
**Is your feature request related to a problem? Please describe.**
I'm trying to understand the behavior of cqlreplicator in certain scenarios. 

**Describe the solution you'd like**
Does cqlreplicator ignore rows that already exist on the TARGET? Or does it copy over the existing data?

**Describe alternatives you've considered**
I've tried reading the code, but I'm not familiar with spark nor scala so my understanding has been slow.

**Additional context**
We're planning to setup a new keyspace and have our services aware of both. During this time, we don't want cqlreplicator to copy a given row if it already exists on the TARGET.

**Comment by jlewis-spotnana** [comment]
This might be a duplicate of (or related to) https://github.com/aws-samples/cql-replicator/issues/69

**Comment by nwheeler81** [comment]
Hi @jlewis-spotnana if don't supply an arbitrary column, e.g.  `--writetime-column colX` the CQLReplicator won't update rows in the target table. So, the CQLReplicator will replicate only inserts and deletes.

**Comment by jlewis-spotnana** [comment]
Hi @nwheeler81 thanks for your response. We're not using `--writetime-column` since our services do not issue UPDATE statements.

We're trying to close a potential race during service cutover from the SOURCE to TARGET table. During cutover (rolling restart), it's possible for our services to write a certain row, say PK1, to the TARGET table. If that same row PK1 already exists in the SOURCE table but cqlreplicator hasn't copied it yet, then cqlreplicator will (eventually) overwrite PK1 on the TARGET.

We would like cqlreplicator to ignore (not copy) Primary Keys which already exist on the TARGET. Is there a way to configure cqlreplicator to ignore existing Primary Keys, given the current code?

I believe this might be what https://github.com/aws-samples/cql-replicator/issues/69 is asking for. (I only found that issue after opening this one.)

**Comment by nwheeler81** [comment]
hi @jlewis-spotnana there is a quick fix in [CQLReplicator.scala](glue/sbin/keyspaces/CQLReplicator.scala) [line](https://github.com/aws-samples/cql-replicator/blob/66677f6ee44dddd013eb796de6d7be932c1a2e91/glue/sbin/keyspaces/CQLReplicator.scala#L688) replace `s"INSERT INTO $trgKeyspaceName.$trgTableName JSON '$jsonRow'"` to `s"INSERT INTO $trgKeyspaceName.$trgTableName JSON '$jsonRow' IF NOT EXISTS"`. It enables [LWT](https://aws.amazon.com/blogs/database/improved-performance-for-lightweight-transactions-with-amazon-keyspaces/) against the target table in Amazon Keyspaces.
I will publish an enhancement that will officially contain this feature in 3-4 weeks.

**Comment by jlewis-spotnana** [comment]
Confirmed the simple patch provided by nwheeler81 works. Thanks for the help!
