### ISSUE TITLE
restart of cqlreplicator fails with "column ... does not exist"

### ISSUE THREAD

**Issue by jlewis-spotnana** [aws-samples/cql-replicator#156]
**Describe the bug**
After restarting cqlreplicator,  the DISCOVERY job fails with the following error:

```
Exception in User Class: org.apache.spark.sql.AnalysisException : Column 'my_primary_key_column' does not exist. Did you mean one of the following? [];
```

The table structure has not changed, so I assume some corruption in cqlreplicator's tracking data (in S3 or the migration.ledger table).

**To Reproduce**
This issue is sporadic. I believe it was caused by the following steps:
1. Run command `./cqlreplicator --state run ...`
2. Let initial DISCOVERY and backfill complete
3. Kill all workers via the AWS Glue console
4. Attempt to restart cqlreplicator with same command

**Expected behavior**
I expect cqlreplicator to restart and continue replication from where it left off.

**Screenshots**
n/a

**Additional context**
This may be related to https://github.com/aws-samples/cql-replicator/issues/112

**Comment by nwheeler81** [comment]
@jlewis-spotnana 
1. go in the S3 folder where the CQLReplicator stores all artifacts, 
2. next find the XXX/YYY/primaryKeys and list all objects.
3. for example, tile_0.head and tile_0.tail (the number of tile_X.head should be equal to the number of tile_X.tail), if it's not try a simple work around: for example, you have the tile_0.head and missing the tile_0.tail, just make a replicate of the tile_0.head to mimic tile_0.tail and so on.
4. start the CQLReplicator again

**Comment by jlewis-spotnana** [comment]
Thanks @nwheeler81 . I copied head to tail as suggested, and cqlreplicator is running again!

What is the affect of copying head to tail in this manner? Is there any risk of losing data when doing this?

**Comment by nwheeler81** [comment]
@jlewis-spotnana there is no risk of losing data, but you will one idle cycle from the discovery Glue job.
