### ISSUE TITLE
Cost Optimization: workers shutdown between DISCOVERY phase runs to save AWS Glue costs

### ISSUE THREAD

**Issue by jlewis-spotnana** [aws-samples/cql-replicator#157]
**Is your feature request related to a problem? Please describe.**
The current implementation of CQLReplicator is very cost inefficient for my use case (AWS Glue costs).

I have a table with over 71M rows with an average row size of 40KB and many rows of max 1024MB. (Total table size 2.7TB) Because of large row size, I need to use cassandra driver setting `max-concurrent-requests = 1` to avoid Keyspaces storage partition throttling.

As a result of the above, the Discovery job takes 16+ hours to complete ONE run through my table. In the mean time, we have several AWS Glue workers totaling 148 DPU sitting idle for 16+ hours.

In-other-words, most of the time our AWS Glue costs are completely wasted.

**Describe the solution you'd like**
I purpose the workers not stay running after the initial Discovery phase. Instead they can startup, do initial copy of all rows (backfill), then SHUTDOWN until the Discovery phase completes again.

**Describe alternatives you've considered**
Here's the workaround I'm using (inspired from Nick's suggestion):

1. start cqlreplicator (cqlreplicator --state run)
2. once workers start, issue `request-stop` (workers will stop, but Discovery continues)
3. wait for Discovery job to stop with `Succeeded`
4. start cqlreplicator again (cqlreplicator --state run)
5. workers will immediately replicate data from last run
6. issue `request-stop` again, workers stop but Discovery job continues 16+ hours
7. wait until Discovery job stops with `Succeeded`
8. repeat from step 4

**Additional context**
We're using CQLReplicator to migrate from a single-region to a multi-region keyspace. Both source and target are in AWS Keyspaces.

EDIT: Added work-around

**Comment by nwheeler81** [comment]
@jlewis-spotnana by default it uses G.2X (might be too big) but you can use [this spreadsheet](https://github.com/aws-samples/cql-replicator/blob/153-add-cloudwatch-support-for-amazon-keyspaces-connector/glue/resources/CQLReplicator-calculator.xlsx) to estimate Glue costs and the throughput against Amazon Keyspaces.

**Comment by nwheeler81** [comment]
@jlewis-spotnana Workaround for stopping Glue jobs after the migration phase is completed: when you started the migration workload and see all Glue job started (run at least 3-4 mins) you can run `request-stop` and it will automatically shutdown all Glue process after the initial migration phase is completed.

**Comment by jlewis-spotnana** [comment]
Hi Nick, thanks for your reply and suggestions! 

The current behavior of cqlreplicator, where workers run continuously, is great for smaller datasets where the Discovery job can finish in a relatively short period of time. However, for larger datasets were Discovery takes 16+ hours, it's not cost-effective to have the workers running the entire time with nothing to do.

In my case, I *do* want cqlreplicator's Discovery job running continuously, but would like the workers to startup only when needed. Your suggestion of issuing a `request-stop` led me to the following work-around.

1. start cqlreplicator (cqlreplicator --state run)
2. once workers start, issue `request-stop` (workers will stop, but Discovery continues)
3. wait for Discovery job to stop with `Succeeded`
4. start cqlreplicator again (cqlreplicator --state run)
5. workers will immediately replicate data from last run
6. issue `request-stop` again, workers stop but Discovery job continues 16+ hours
7. wait until Discovery job stops with `Succeeded`
8. repeat from step 4

The above is very high-touch, but prevents the workers from sitting idle for 16+ hours, saving a ton of money in my case.

If the stopping and starting of workers could be automated, that would be a great benefit.

**Comment by nwheeler81** [comment]
@jlewis-spotnana 
1. If you want to replicate only the historical workload and release Glue resources once it's completed, add the following flag `--workload-type batch` to the command line, for example:
`cqlreplicator --state run --tiles 8 --landing-zone s3://cql-replicator-1234567890-us-west-2 --region us-west-2 --writetime-column col3 --src-keyspace ks_test_cql_replicator --src-table test_cql_replicator --trg-keyspace ks_test_cql_replicator --trg-table test_cql_replicator --inc-traffic **--workload-type batch**`
2. To improve performance of  the discovery process (reduce 16+ hrs), double or triple the number of discovery DPUs, e.g. `--override-discovery-workers 20`
3. After the first round is completed you can reduce the number of DPUs, by increasing the default value `--orw 2000000` or higher.
4. Consider to compress, split or offload to Amazon S3 large rows.

**Comment by jlewis-spotnana** [comment]
Thanks Nick. I just recently became aware of the `--workload-type batch` flag which might help in my case. The `--override-discovery-workers` flag is also something I'm looking at.

Pushing larger rows to S3 is possible but will require more engineering time to implement.

Thanks for your suggestions!

**Comment by nwheeler81** [comment]
@jlewis-spotnana I just added this feature recently, pull the repo
