### ISSUE TITLE
nested_object conversion issue

### ISSUE THREAD

**Issue by dubrovine** [aws-samples/cql-replicator#165]
https://github.com/aws-samples/cql-replicator/blob/24cc53f1b8c80c81204165cf4dbb55c1915920fc/glue/sbin/keyspaces/CQLReplicator.scala#L174

if we have such scheme in aws keyspaces

```
CREATE TABLE channel.channels (
    id timeuuid PRIMARY KEY,
    alias text,
    company_id text,
    created timestamp,
    description text,
    name text,
    photo text,
    sessiondata text,
    sessionid timeuuid,
    sessionlastid timeuuid,
    state text,
    type text,
    updated timestamp,
    user frozen<user>,
    users map<text, text>
)
```

users `map<text, text>` generating nested_object like (when we exporting it from cassandra table):

`"users":"{\"g.Wngn-ynR5hl-AAAC\":{\"id\":\"g.Wngn-ynR5hl-AAAC\",\"name\":null,\"photo\":null,\"type\":\"g\",\"t\":null}}"`

there is no change to store string like this so processed string should looks like: 

`users":"{\"g.Wngn-ynR5hl-AAAC\":\"{\\\"id\\\":\\\"g.Wngn-ynR5hl-AAAC\\\",\\\"name\\\":null,\\\"photo\\\":null,\\\"type\\\":\\\"g\\\",\\\"t\\\":null}\"}"`

**Comment by nwheeler81** [comment]
Hi @dubrovine, I tried to replicate your issue, here is my result:
Source:
![image](https://github.com/user-attachments/assets/2f012d1d-08be-4070-a3a9-899f0f007c0b)
Target:
![image](https://github.com/user-attachments/assets/7b9855b2-f9a1-41eb-b51d-fae17c6090a0)
Both your examples replicated as is with no changes.

**Comment by dubrovine** [comment]
Sorry. I forgot to mention that we are trying to replicate from UDT

here is the original cassandra scheme:

```
`CREATE TABLE channel.channels (
    id timeuuid PRIMARY KEY,
    alias text,
    company_id text,
    created timestamp,
    description text,
    name text,
    photo text,
    sessiondata text,
    sessionid timeuuid,
    sessionlastid timeuuid,
    state text,
    type text,
    updated timestamp,
    user frozen<user>,
    users map<text, frozen<user>>
)`
```

`users map<text, frozen<user>>`

here is keyspaces scheme:

```
`CREATE TABLE channel.channels (
    id timeuuid PRIMARY KEY,
    alias text,
    company_id text,
    created timestamp,
    description text,
    name text,
    photo text,
    sessiondata text,
    sessionid timeuuid,
    sessionlastid timeuuid,
    state text,
    type text,
    updated timestamp,
    user text,
    users map<text, text>
)`

```
`users map<text, text>`

so we trying to avoid UDTs and using text (json string instead)


for example we exports one record from cassandra & receiving such query 

`INSERT INTO channel.channels JSON '{"id":"c6f05420-0f1c-11e8-8ca4-eff552a6d2cd","alias":null,"company_id":"i88430253129","created":"2018-02-11 11:14:50.596Z","description":null,"name":"test","photo":null,"sessiondata":null,"sessionid":null,"sessionlastid":null,"state":null,"type":"help","updated":null,"user":"{\"id\":\"g.Wngn-ynR5hl-AAAC\",\"name\":null,\"photo\":null,\"type\":\"g\",\"t\":null}","users":"{\"g.Wngn-ynR5hl-AAAC\":{\"id\":\"g.Wngn-ynR5hl-AAAC\",\"name\":null,\"photo\":null,\"type\":\"g\",\"t\":null}}"}'
`

I am trying to insert directly into keyspaces table & got error

<img width="1353" alt="Снимок экрана 2024-10-04 в 08 05 45" src="https://github.com/user-attachments/assets/5be159f1-9705-4a22-89ba-c90e718f44e0">

**Comment by nwheeler81** [comment]
@dubrovine I think, the problem is in the structure map<text, frozen<user>> that has V defined by the frozen UDT. Currently, the CQLReplicator can transform only non-nested UDTs, for example, the user: frozen<user> column maps to user: text in the target table. Let me check if there is quick workarounds.

**Comment by nwheeler81** [comment]
@dubrovine you are missing double quotes around UDT inside MAP: "users":"{\"g.Wngn-ynR5hl-AAAC\":**_"_**{\"id\":\"g.Wngn-ynR5hl-AAAC\",\"name\":null,\"photo\":null,\"type\":\"g\",\"t\":null}**_"_**}".

**Comment by dubrovine** [comment]
yeap. you're right (I was mentioned it in the first comment)
is it possible to add double quotes in [CQLReplicator.scala](https://github.com/aws-samples/cql-replicator/blob/24cc53f1b8c80c81204165cf4dbb55c1915920fc/glue/sbin/keyspaces/CQLReplicator.scala#L174) ?

**Comment by nwheeler81** [comment]
@dubrovine I've added another support function to transform nested UDT objects in collections to text (MAP<Type, UDT> to MAP<Type, Text<): 
![image](https://github.com/user-attachments/assets/74f1ede2-0130-4600-8bc7-7c7ebfda258e)
Limitations: Supports only Map structure. Pleas use [this branch](https://github.com/aws-samples/cql-replicator/tree/165-nested_object-conversion-issue) to test it your environment. Please, keep me posted after your tests I will merge it.

**Comment by dubrovine** [comment]
hello there. 
to be honest we didn't have time to check everything carefully 
since we received this news [AWS KEYSPACES UDT SUPPORT](https://aws.amazon.com/ru/about-aws/whats-new/2024/10/amazon-keyspaces-apache-cassandra-user-defined-types/)

actually THIS seems like fix everything and we don't need to make any conversion
