### ISSUE TITLE
[CQLReplicator on Glue] Set replication starting timestamp

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#85]
Is it possible to have the same functionality as the ECS version about `ENABLE_REPLICATION_POINT` and `STARTING_REPLICATION_TIMESTAMP`?

https://github.com/aws-samples/cql-replicator/blob/main/ecs/README.MD?plain=1#L121-L122

Basically, replicating data after a specific point of time, not all the data.

**Comment by nwheeler81** [comment]
yeah, it's possible.

**Comment by nwheeler81** [comment]
1/ Add a flag `--start-replication-from [epoch-time]` in `cqlreplicator` and `CQLReplicator.scala`. Works only in combination with `--writetime-column [regular-column]`.
2/ Replicates rows if `writetime(regular-column)>epoch-time`
3/ Add a filter statement in `keysDiscoveryProcess()`:  `val primaryKeysDf = sparkSession.read.option("inferSchema", "true").table(source).persist(StorageLevel.DISK_ONLY)`
4/ Add checks:  regular-column is supplied,  epoch-time is greater 0
