### ISSUE TITLE
[CQLReplicator on Glue] Enable Glue metrics

### ISSUE THREAD

**Issue by hungfaileung** [aws-samples/cql-replicator#86]
The metrics are not enabled by default in Glue.
It would be great if it can be enabled when the job is created (i.e. `init`).

**Comment by nwheeler81** [comment]
well, I can add it, possible, but Glue/Spark is chatty and it might incur extra CloudWatch costs

**Comment by timota** [comment]
probably add it as a flag during init process ?

**Comment by nwheeler81** [comment]
--enhanced-monitoring-enabled
