### ISSUE TITLE
glue app job parameter value over 256 characters

### ISSUE THREAD

**Issue by frozensky** [aws-samples/cql-replicator#97]
when I check the CQLReplicator under Glue, I see the Job parameter error.  Attach screenshot for review.
```
The maximum number of characters you can use in a parameter value is 256.
```

**Comment by nwheeler81** [comment]
is it preventing you to execute `cqlreplicator --state  run`?

Note that during the init stage CQLReplicator deploys the Glue job `CQLReplicator.scala` via `aws` cli with spark conf parameters and there is no specific quota for the max number of characters.
